sudo: false

language: c

addons:
  apt:
    packages:
      - libgmp-dev

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

matrix:
  include:
  - env: ARGS=""
  #- env: ARGS="--resolver lts-6"
  #- env: ARGS="--resolver lts"

script:
- stack $ARGS --no-terminal --install-ghc test --haddock --no-haddock-deps
