version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "stack.yaml" }}-{{ checksum "mailchimp.cabal" }}
            - v1-stack-{{ checksum "stack.yaml" }}
      - run:
          command: stack build --test --only-dependencies
      - save_cache:
          key: v1-stack-{{ checksum "stack.yaml" }}-{{ checksum "mailchimp.cabal" }}
          paths:
            - ~/.stack/
      - run:
          command: stack build
      - run:
          command: stack build --test
